---
# Tasks for hosts in `control` group (hosts, where i will _never_ want to
# install OS).

- block:
    - name: Ensure pxe hosts config directory exists
      file:
        dest:   "{{ pxe_hosts_cfg_dir }}"
        state:  directory
    - name: Copy header and footer pxe configs, if generating full menu
      copy:
        src:    "{{ item }}"
        dest:   "{{ pxe_hosts_cfg_dir + '/' + item | basename }}"
        owner:  root
        group:  root
        mode:   0640
        force:  yes
        backup: no
      loop:
        - "pxelinux/00_pxelinux_header.cfg"
        - "pxelinux/99_pxelinux_footer.cfg"
      when: pxe_full_menu
    - name: Or delete header and footer pxe configs, if generating only menu items
      file:
        dest:   "{{ pxe_hosts_cfg_dir + '/' + item | basename }}"
        state:  absent
      loop:
        - "pxelinux/00_pxelinux_header.cfg"
        - "pxelinux/99_pxelinux_footer.cfg"
      when: not pxe_full_menu
    - name: Generate pxe Hosts menu item
      assemble:
        src: "{{ pxe_hosts_cfg_dir }}"
        regexp: "[0-9]_[^/]+\\.cfg$"
        dest: "{{ pxelinux_host_cfg }}"
  when: inventory_hostname in groups['pxe']

