---

- block:
    - name: define | Define pxe server
      set_fact:
        _pxe_server: >-
          {{ os_install.pxe_server | default(groups['pxe_servers'] | first) }}

    - name: define | Define OS install config
      set_fact:
        _host_conf: >-
          {{  { 'raid': default_raid
              , 'lvm' : default_lvm
              , 'vg_name' : item_name
              , 'rootpw'  : lookup('file',
                              lookup('first_found',
                                [ 'passwords/' + item_name
                                , 'passwords/default'
                                ])
                              )
              , 'disks' : ['sda', 'sdb'] if item_raid else ['sda']
              , 'gen_ks' : true
              , 'gen_pxe_host' : true
              } | combine(os_install,
                    { 'name'    : item_name
                    , 'pxe_cfg' : hosts_pxe_menu_cfg_d + '/50_' + item_name + '.cfg'
                    , 'ks_cfg'  : hostvars[item_ks_server].ks_www_root + '/' + item_name + '.cfg'
                    , 'ks_www'  : hostvars[item_ks_server].ks_www_addr + '/' + item_name + '.cfg'
                    }
                  )
          }}
      vars:
        item_name: >-
          {{ os_install.name | default(inventory_hostname) }}
        item_raid: >-
          {{ os_install.raid | default(default_raid) }}
        item_ks_server: >-
          {{ os_install.ks_server | default(groups['ks_servers'] | first) }}

    - name: define | Define OS install network config
      set_fact:
        _host_conf: >-
          {{  _host_conf | combine({'net' : item_net}) }}
      vars:
        item_ip0_network: >-
          {{ os_install.net[0].ip | ipaddr('network') }}
        def_ip0: >-
          {{  { 'gw' : default_net[item_ip0_network].gw
                        if default_net[item_ip0_network].gw is defined
                        else os_install.net[0].gw
              , 'ns' : default_net[item_ip0_network].ns
                        if default_net[item_ip0_network].ns is defined
                        else os_install.net[0].ns
              } if default_net[item_ip0_network] is defined
                else
                { 'gw' : os_install.net[0].gw
                , 'ns' : os_install.net[0].ns
                }
          }}
        item_net: >-
          {{ [def_ip0 | combine(os_install.net[0])] + os_install.net[1:] }}
      when: os_install.net is defined

    - name: define | Show OS install config
      debug:
        var: _host_conf

  when: inventory_hostname in groups['servers']

- block:
    - name: images | Define pxe OS config
      set_fact:
        _pxe_os: >-
          {{ item_os | combine(
                { 'name' : item_name
                , 'checksum_url'  : item_checksum_url
                , 'checksum_dir'  : item_checksum_dir
                , 'checksum_file' : item_checksum_dir + '/' + item_os.checksum_fn
                , 'pxe_dir'       : item_pxe_dir
                , 'pxe_kernel'    : item_pxe_dir + '/' + item_os.iso_kernel | basename
                , 'pxe_initrd'    : item_pxe_dir + '/' + item_os.iso_initrd | basename
                , 'pxe_menu_cfg_d' : item_pxe_menu_cfg_d
                , 'pxe_cfg'       : item_pxe_menu_cfg_d + '/50_' + item_name + '.cfg'
                }
              )
          }}
      vars:
        item_name: >-
          {{ _host_conf['os'] }}
        item_os: >-
          {{ pxe_os[item_name] }}
        item_checksum_url: >-
          {{ item_os.checksum_url | default(item_os.url) + '/' + item_os.checksum_fn }}
        item_checksum_dir: >-
          {{ images_checksum_dir + '/' + item_name }}
        item_pxe_dir: >-
          {{ item_name }}
        item_pxe_menu_cfg_d: >-
          {{ hostvars[_pxe_server].pxe_cfg_d_path
                + '/' + item_os.pxe_menu_cfg | basename | splitext | first }}

    - name: images | Show pxe OS config
      debug:
        var: _pxe_os

