---

- block:
    - name: define (pxe_server) | Define pxe server config
      set_fact:
        _pxe_root_path: >-
          {{ item_pxe_root_path }}
        _pxe_cfg_d_path: >-
          {{ hostvars[_pxe_server].pxe_cfg_d_path | default(item_pxe_root_path + '/pxelinux_menus.d') }}
        _tftp_address: >-
          {{ hostvars[_pxe_server].tftp_address
                | default(hostvars[_pxe_server].ansible_default_ipv4.address + ':69')
          }}
        _pxelinux_cfg: >-
          {{ item_pxelinux_cfg }}
        _pxelinux_incl_dir: >-
          {{ hostvars[_pxe_server].pxelinux_incl_dir | default(item_pxelinux_cfg | dirname) }}
      vars:
        item_pxe_root_path: >-
          {{ hostvars[_pxe_server].pxe_root_path | default('/srv/tftp') }}
        item_pxelinux_cfg: >-
          {{ hostvars[_pxe_server].pxelinux_cfg | default('pxelinux.cfg/default') }}
      delegate_facts: true
      delegate_to: "{{ _pxe_server }}"

    - name: define | Show pxe server config
      debug:
        msg: "{{ item + ': ' + hostvars[_pxe_server][item] }}"
      loop:
        - '_pxe_root_path'
        - '_pxe_cfg_d_path'
        - '_tftp_address'
        - '_pxelinux_cfg'
        - '_pxelinux_incl_dir'

- block:
    - name: define | Define pxe menus config
      set_fact:
        _pxe_menus: >-
          {{ _pxe_menus | combine(
                { item : item_pxe_menu
                    | combine(
                        { 'cfg_d' : hostvars[_pxe_server]._pxe_cfg_d_path + '/' + item
                        , 'cfg'   : hostvars[_pxe_server]._pxelinux_incl_dir + '/' + item + '.cfg'
                        })
                })
          }}
      vars:
        item_pxe_menu: >-
          {{ pxe_menus[item] | default(
                  { 'desc' : item + ' (undefined pxe menu name)'
                                if item != hosts_pxe_menu
                                else 'Hosts'
                  })
          }}
      loop: >-
        {{ pxe_os.values()
                | selectattr('pxe_menu', 'defined')
                | map(attribute='pxe_menu')
                | unique() | list
              + [hosts_pxe_menu] }}

    - name: define | Show pxe OS menus config
      debug:
        var: _pxe_menus

- block:
    - name: define | Define OS install config
      set_fact:
        pxe_root_path: "{{ hostvars[_pxe_server]._pxe_root_path }}"
        _install_conf: >-
          {{  { 'raid': default_raid
              , 'lvm' : default_lvm
              , 'vg_name' : item_name
              , 'rootpw'  : lookup('file',
                              lookup('first_found',
                                [ 'passwords/' + item_name
                                , 'passwords/default'
                                ])
                              )
              , 'disks' : ['sda', 'sdb'] if item_raid else ['sda']
              , 'gen_ks' : true
              , 'gen_pxe_host' : true
              } | combine(os_install,
                    { 'name'    : item_name
                    , 'pxe_cfg' : _pxe_menus[hosts_pxe_menu].cfg_d + '/50_' + item_name + '.cfg'
                    , 'ks_cfg'  : hostvars[_kickstart_server].ks_www_root + '/' + item_name + '.cfg'
                    , 'ks_www'  : hostvars[_kickstart_server].ks_www_addr + '/' + item_name + '.cfg'
                    }
                  )
          }}
      vars:
        item_name: >-
          {{ os_install.name | default(inventory_hostname) }}
        item_raid: >-
          {{ os_install.raid | default(default_raid) }}

    - name: define | Define OS install network config
      set_fact:
        _install_conf: >-
          {{  _install_conf | combine({'net' : item_net}) }}
      vars:
        item_ip0_network: >-
          {{ os_install.net[0].ip | ipaddr('network') }}
        def_ip0: >-
          {{  { 'gw' : default_net[item_ip0_network].gw
                        if default_net[item_ip0_network].gw is defined
                        else os_install.net[0].gw
              , 'ns' : default_net[item_ip0_network].ns
                        if default_net[item_ip0_network].ns is defined
                        else os_install.net[0].ns
              } if default_net[item_ip0_network] is defined
                else
                { 'gw' : os_install.net[0].gw
                , 'ns' : os_install.net[0].ns
                }
          }}
        item_net: >-
          {{ [def_ip0 | combine(os_install.net[0])] + os_install.net[1:] }}
      when: os_install.net is defined

    - name: define | Show OS install config
      debug:
        var: _install_conf

  when: inventory_hostname in groups['servers']

- block:
    - name: define | Define pxe OS config
      set_fact:
        _pxe_os: >-
          {{ item_os | combine(
                { 'name' : item_name
                , 'checksum_url'  : item_checksum_url
                , 'checksum_dir'  : item_checksum_dir
                , 'checksum_file' : item_checksum_dir + '/' + item_os.checksum_fn
                , 'pxe_dir'       : item_pxe_dir
                , 'pxe_kernel'    : item_pxe_dir + '/' + item_os.iso_kernel | basename
                , 'pxe_initrd'    : item_pxe_dir + '/' + item_os.iso_initrd | basename
                , 'pxe_menu_cfg'  : hostvars[_pxe_server]._pxelinux_incl_dir
                                      + '/' + item_os.pxe_menu + '.cfg'
                , 'pxe_menu_cfg_d' : item_pxe_menu_cfg_d
                , 'pxe_cfg'       : item_pxe_menu_cfg_d + '/50_' + item_name + '.cfg'
                , 'gen_pxe_os'  : item_os.gen_pxe_os | default(true)
                }
              )
          }}
      vars:
        item_name: >-
          {{ _install_conf['os'] }}
        item_os: >-
          {{ pxe_os[item_name] }}
        item_checksum_url: >-
          {{ item_os.checksum_url | default(item_os.url) + '/' + item_os.checksum_fn }}
        item_checksum_dir: >-
          {{ images_checksum_dir + '/' + item_name }}
        item_pxe_dir: >-
          {{ item_name }}
        item_pxe_menu_cfg_d: >-
          {{ hostvars[_pxe_server]._pxe_cfg_d_path + '/' + item_os.pxe_menu }}

    - name: define | Show pxe OS config
      debug:
        var: _pxe_os

