---

- block:
    - name: images | Define host pxe OS
      set_fact:
        _pxe_os: >-
          {{ cur_os | combine(
                { 'name' : cur_os_name
                , 'checksum_url'  : cur_os.url + '/' + cur_os.checksum_fn
                , 'checksum_dir'  : os_checksum_dir
                , 'checksum_file' : os_checksum_dir + '/' + cur_os.checksum_fn
                }
              )
          }}
      vars:
        cur_os_name: "{{ _os_install['os'] }}"
        cur_os: "{{ pxe_os[cur_os_name] }}"
        os_checksum_dir: "{{ images_checksum_dir + '/' + cur_os_name }}"

    - name: images | Show pxe OS definitions
      debug:
        var: _pxe_os

- block:
    - name: images (localhost) | Create image checksum directories
      file:
        name: "{{ _pxe_os.checksum_dir }}"
        state: directory

    - name: images (localhost) | Download checksum file
      get_url:
        url:  "{{ _pxe_os.checksum_url }}"
        dest: "{{ _pxe_os.checksum_file }}"
        #{{ image_checksum_dir + '/' + item.checksum_url | urlsplit('path') | basename }}
        force: yes

    - name: images (localhost) | Read checksum file
      set_fact:
        _os_iso: >-
          {{ { 'iso_name'  : cur_iso_name
             , 'iso_url'   : _pxe_os.url + '/' + cur_iso_name
             , 'iso_dest'  : cur_iso_dest
             , 'iso_file'  : cur_iso_dest + '/' + cur_iso_name
             , 'os_files'  : [_pxe_os.kernel, _pxe_os.initrd]
             }
          }}
      vars:
        cur_iso_name: >-
          {{ lookup('file', _pxe_os.checksum_file)
                | regex_search(_pxe_os.checksum_iso_name_rx, multiline=true)
          }}
        cur_iso_dest: >-
          {{ pxe_dir + '/' + _pxe_os.name + '-huy' }}

    - name: images | Show OS image definitions
      debug:
        var: _os_iso

  delegate_to: localhost

- block:
    - name: images (pxe_server) | Create image checksum directories
      file:
        name: "{{ _os_iso.iso_dest }}"
        state: directory

    - name: images (pxe_server) | Download iso
      get_url:
        url:  "{{ _os_iso.iso_url }}"
        dest: "{{ _os_iso.iso_file }}"
        force: no

    - name: images (pxe_server) | Extract kernel and initrd
      iso_extract:
        image:  "{{ _os_iso.iso_file }}"
        dest:   "{{ _os_iso.iso_dest }}"
        files:  "{{ _os_iso.os_files }}"
        force:  true

  delegate_to: "{{ pxe_server }}"

