---

# Enforce correct state of kickstart and pxe host configs: create for hosts in
# `new` group and delete for hosts in `installed` group. Hosts in other groups
# are _ignored_.
- block:
    - name: kickstart | Create config for new hosts
      template:
        src: "{{ _install_conf.os }}.cfg"
        force: yes
        backup: no
        mode: 0755
        dest: "{{ _install_conf.ks_cfg }}"
      when: _install_conf.gen_ks and inventory_hostname in groups['new']

    - name: kickstart | Delete config for _already_ installed hosts
      file:
        dest: "{{ _install_conf.ks_cfg }}"
        state: absent
      when: not _install_conf.gen_ks or inventory_hostname in groups['installed']

  when: inventory_hostname in groups['servers']
  delegate_to: "{{ _kickstart_server }}"

