---

- block:
    - name: define | Define pxe server
      set_fact:
        _pxe_server: >-
          {{ pxe_server | default(groups['pxe_servers'] | first) }}
        _kickstart_server: >-
          {{ kickstart_server | default(groups['kickstart_servers'] | first) }}

    - name: Gather facts about pxe server
      setup:
      loop:
        - "{{ _pxe_server }}"
        - "{{ _kickstart_server }}"
      delegate_to: "{{ item }}"
      delegate_facts: true

  tags:
    - always

- name: Define variables.
  import_tasks: define.yml
  tags:
    - always

- name: Configure pxe.
  import_tasks: pxe.yml
  tags:
    - pxe

- name: Configure kickstart.
  import_tasks: kickstart.yml
  tags:
    - kickstart
    - pxe_host

- name: Update pxe images
  import_tasks: images.yml
  tags:
    - image

- block:
    - name: Print host access details
      debug:
        msg: "{{ msg_header.split('\n') + msg_ips }}"
      vars:
        msg_header: |-
          Server '{{ inventory_hostname }}' access details:
          {{ _pxe_os.desc }}, root, {{ _install_conf.rootpw }}
        msg_ips: >-
          {{ _install_conf.net | map(attribute='ip') | map('ipaddr', 'address') | list }}

    - name: Sending all access details to email
      community.general.mail:
        host: "{{ mail_report_config.host }}"
        port:   "{{ mail_report_config.port   | default(omit) }}"
        secure: "{{ mail_report_config.secure | default(omit) }}"
        username: "{{ mail_report_config.username }}"
        password: "{{ lookup('file', 'mail_passwords/' + mail_report_config.username) }}"
        to:     "{{ mail_report_config.to     | default(mail_report_config.username) }}"
        sender: "{{ mail_report_config.sender | default(mail_report_config.username) }}"
        subject: >-
          {{ 'Ansible: Server(s) '
              + ansible_play_hosts | map('regex_replace', '_', '-') | join(', ')
              + ' access details'
          }}
        # ' match quotes for broken highlighting.
        body: "{{ lookup('template', './templates/access_details_email.txt') }}"
        headers: "{{ mail_report_config.headers | default(omit) }}"
      when: mail_report_config.host is defined
      run_once: true
      delegate_to: localhost

  when: inventory_hostname in groups['new'] and not inventory_hostname in groups['dummy']
  tags:
    - access_details
    - always
