---

# Here're two blocks: first is for preparing everything needed for host,
# _where_ i want to install OS. And the second is for configuring _pxe server
# itself_. The pxe server configuration task should be run _strictly after_
# all host tasks have been _finished_. But i can't ensure this ordering from a
# role. So, this should be done from main playbook, by first launching the
# role for hosts in `servers`, and then for hosts in `control` group.

- name: Define variables.
  import_tasks: define.yml

- name: Configure pxe.
  import_tasks: pxe.yml

- name: Configure kickstart.
  include_tasks: kickstart.yml

