---

- name: Define variables.
  import_tasks: define.yml

- name: Configure pxe.
  import_tasks: pxe.yml

- name: Configure kickstart.
  include_tasks: kickstart.yml

- name: Update pxe images
  import_tasks: images.yml
  tags:
    - image
