---

- block:
    - name: define | Define pxe server
      set_fact:
        _pxe_server: >-
          {{ pxe_server | default(groups['pxe_servers'] | first) }}
        _kickstart_server: >-
          {{ kickstart_server | default(groups['kickstart_servers'] | first) }}

    - name: Gather facts about pxe server
      setup:
      loop:
        - "{{ _pxe_server }}"
        - "{{ _kickstart_server }}"
      delegate_to: "{{ item }}"
      delegate_facts: true

  tags:
    - always

- name: Define variables.
  import_tasks: define.yml
  tags:
    - always

- name: Update pxe images
  import_tasks: images.yml
  tags:
    - image

- name: Configure pxe.
  import_tasks: pxe.yml
  tags:
    - pxe

- name: Configure kickstart.
  import_tasks: kickstart.yml
  tags:
    - kickstart
