---

- name: Define variables.
  import_tasks: define.yml
  tags:
    - always

- name: Configure pxe.
  import_tasks: pxe.yml
  tags:
    - pxe

- name: Configure kickstart.
  import_tasks: kickstart.yml
  tags:
    - kickstart

- name: Update pxe images
  import_tasks: images.yml
  tags:
    - image
