---

- block:
    - name: pxe (pxe_server) | Install tftpd and pxelinux packages
      package:
        name:
          - 'tftpd-hpa'
          - 'pxelinux'
          - 'syslinux-common'
        state: present

    - name: pxe (pxe_server) | Ensure pxe directories exist
      file:
        dest: "{{ item }}"
        state: directory
      loop:
        - "{{ pxe_root_path }}"
        - "{{ pxe_modules_path }}"
        - "{{ pxe_root_path + '/pxelinux.cfg' }}"
      notify:
        - restart tftpd

    - name: pxe (pxe_server) | Set pxe root directory in tftp server
      lineinfile:
        path: '/etc/default/tftpd-hpa'
        backup: yes
        regexp: '^TFTP_DIRECTORY='
        line: "{{ 'TFTP_DIRECTORY=\"' + pxe_root_path + '\"' }}"
      notify:
        - restart tftpd

    - name: pxe (pxe_server) | Set tftp server listen address
      lineinfile:
        path: '/etc/default/tftpd-hpa'
        backup: yes
        regexp: '^TFTP_ADDRESS='
        line: "{{ 'TFTP_ADDRESS=\"' + hostvars[_pxe_server]._tftp_address + '\"' }}"
      notify:
        - restart tftpd

    - name: pxe (pxe_server) | Copy pxelinux.0
      copy:
        src:  "{{ item }}"
        dest: "{{ pxe_root_path + '/' + item | basename }}"
        remote_src: yes
      vars:
        item: '/usr/lib/PXELINUX/pxelinux.0'

    - name: pxe (pxe_server) | Find syslinux modules
      find:
        paths: '/usr/lib/syslinux/modules/bios'
      register: syslinux_modules

    - name: pxe (pxe_server) | Copy syslinux modules
      copy:
        src:  "{{ item.path }}"
        dest: "{{ pxe_modules_path + '/' + item.path | basename }}"
        remote_src: yes
      loop: "{{ syslinux_modules.files }}"

  delegate_to: "{{ _pxe_server }}"
  tags:
    - install_pxe

# Enforce correct state of kickstart and pxe (pxe_server) host configs: create for hosts in
# `new` group and delete for hosts in `installed` group. Hosts in other groups
# are _ignored_.

- block:
    - name: pxe (pxe_server) | Ensure directories for pxe configs exist
      file:
        dest:   "{{ item }}"
        state:  directory
      loop:
        - "{{ hosts_pxe_menu_cfg_d }}"
        - "{{ _pxe_os.pxe_menu_cfg_d }}"

    - name: pxe (pxe_server) | Create config for host OS
      template:
        src:  "pxe_os.cfg"
        force:  yes
        backup: yes
        dest: "{{ _pxe_os.pxe_cfg }}"
      register: pxe_os_added

    - name: pxe (pxe_server) | Generate OS menu
      assemble:
        src: "{{ _pxe_os.pxe_menu_cfg_d }}"
        regexp: "[0-9]_[^/]+\\.cfg$"
        dest: >-
          {{ pxe_root_path
              + '/' + hostvars[_pxe_server]._pxelinux_incl_dir
              + '/' + _pxe_os.pxe_menu_cfg
          }}
      when: force_overwrite or pxe_os_added.changed

    - name: pxe (pxe_server) | Create config for new host
      template:
        src:  "pxe_host.cfg"
        force:  yes
        backup: yes
        dest: "{{ _host_conf.pxe_cfg }}"
      register: pxe_hosts_added
      when: _host_conf.gen_pxe_host and inventory_hostname in groups['new']

    - name: pxe (pxe_server) | Or delete config for installed host
      file:
        dest: "{{ _host_conf.pxe_cfg }}"
        state: absent
      register: pxe_hosts_deleted
      when: not _host_conf.gen_pxe_host or inventory_hostname in groups['installed']

    - name: pxe (pxe_server) | Generate Hosts menu
      assemble:
        src: "{{ hosts_pxe_menu_cfg_d }}"
        regexp: "[0-9]_[^/]+\\.cfg$"
        dest: >-
          {{ pxe_root_path
              + '/' + hostvars[_pxe_server]._pxelinux_incl_dir
              + '/' + hosts_pxe_menu_cfg
          }}
      when: force_overwrite or pxe_hosts_added.changed or pxe_hosts_deleted.changed

  when: inventory_hostname in groups['servers']
  delegate_to: "{{ _pxe_server }}"

- block:
    - name: pxe (pxe_server) | Copy files used in pxelinux config
      copy:
        src:  "{{ item }}"
        dest: "{{ pxe_root_path + '/' + item | basename }}"
      loop:
        - "{{ pxe_menu_font }}"
        - "{{ pxe_splash }}"

    - name: pxe (pxe_server) | Copy additional pxe menus config file
      copy:
        src:  "{{ item }}"
        dest: "{{ pxe_root_path + '/' + addon_pxe_menus_cfg }}"
      vars:
        item: >-
          {{ lookup('first_found', [addon_pxe_menus_file, 'files/addon_pxe_menus']) }}

    - name: pxe (pxe_server) | Generate main pxelinux config
      template:
        src:  'pxelinux_cfg'
        dest: "{{ pxe_root_path + '/pxelinux.cfg/default' }}"
        force: yes
        backup: yes
      vars:
        pxe_menus: >-
          {{ pxe_os.values() | map(attribute='pxe_menu') | unique | list }}

  delegate_to: "{{ _pxe_server }}"

