---

- name: Gather facts
  hosts: all:!servers

- name: Configure bh auto install
  hosts: all
  gather_facts: no
  roles:
    - bh-auto-install
  vars:
    default_net: >-
      {{  { '192.168.1.0':
              { 'gw': '192.168.1.1'
              , 'ns': '192.168.1.1'
              }
          }
      }}
    mail_report_config: >-
      {{
          { 'host': 'mail.example.com'
          , 'port': '2525'
          }
      }}

